### ISSUE TITLE
call send function with length 0

### ISSUE THREAD

**Issue by nuft** [Stapelzeiger/serial-datagram#8]
I suggest not calling the send function in `serial_datagram_send ` if the buffer length is zero.

for example [here](https://github.com/Stapelzeiger/serial-datagram/blob/master/serial_datagram.c#L27) insert:
``` C
if (b - a > 0) {
    send_fn(sendarg, &dtgrm_byte[a], b - a);
}
```

**Comment by Stapelzeiger** [comment]
The send_fn should be able to handle a length of 0. (most write functions do)
